"""ix added

Revision ID: 1eaf8de9cbbd
Revises: 3d68d3a6470d
Create Date: 2026-02-06 16:57:54.522211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eaf8de9cbbd'
down_revision: Union[str, Sequence[str], None] = '3d68d3a6470d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_categories_parent_id', 'categories', ['parent_id'], unique=False)
    op.drop_index(op.f('ix_orders_items_order_id'), table_name='order_items')
    op.create_index('ix_order_items_product_id', 'order_items', ['product_id'], unique=False)
    op.drop_index(op.f('ix_orders_create_at'), table_name='orders')
    op.create_index('ix_orders_created_at', 'orders', ['created_at'], unique=False)
    op.create_index('ix_orders_customer_id', 'orders', ['customer_id'], unique=False)
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_index('ix_orders_customer_id', table_name='orders')
    op.drop_index('ix_orders_created_at', table_name='orders')
    op.create_index(op.f('ix_orders_create_at'), 'orders', ['created_at'], unique=False)
    op.drop_index('ix_order_items_product_id', table_name='order_items')
    op.create_index(op.f('ix_orders_items_order_id'), 'order_items', ['order_id'], unique=False)
    op.drop_index('ix_categories_parent_id', table_name='categories')
    # ### end Alembic commands ###
